README.md
- added new TOC members
- updated Pricinples CaSe issue
=> updated new members

CONTRIBUTING.md, CONTRIBUTORS.md, EMERITUS.md
adding 2 files for contributors (list), and contributing guidlines
=> Add contributor md files for basics of contributor guidance

CONTRIBUTING.md
=> Fix broken link to contributors file

CODE_OF_CONDUCT.md
Update code of conduct to state "official" events
=> Update code of conduct to state "official" events

GROUPS.md
This is a followup to the original document, available at: https://docs.google.com/document/d/1c33ML-lLCewrDjGxCisRxbwqcl21kmAjJ62GbgAaRFY/edit and discussed in the last two TOC meetings.
=> Add Working Group and SIG procedure and lifecycle.

proposals/securitysig.md
=> Add Security SIG proposal

CODE_OF_CONDUCT.md
=> Update CoC to remove "Draft" reference

sigs/proposed.md
First cut describing the areas of interest
=> A description for MLOps

sigs/sig-mlops.md
This is draft proposal for MLOps Sig
=> Proposal for MLOps Sig

README.md, meeting_notes/TOC_Meeting_Notes.md
Now publishing meeting notes via github repo.
=> Cdf meeting updates

process/graduation_criteria.md
DRAFT proposal for graduation criteria
=> project lifecycle additions - graduation criteria

PROJECT_LIFECYCLE.md, process/graduation_criteria.md
- CII badging
- Security Audit
=> Add requirements to the CDF Graduation criteria:

README.md
-Modified formatting to shorten calendar link
=> Update TOC Communication Section

sigs/best-practices-sig.md
This PR contains the Best Practices SIG proposal
=> Best Practices SIG proposal

README.md
Hi,
The link of telemetry on README.md is broke, I think the correct link is [Telemetry data collection and usage policy](https://www.linuxfoundation.org/telemetry-data-collection-and-usage-policy/).
Best,
=> Fixed Telemtry and Data Collection Policy

sigs/README.md, sigs/sig-events.md
This is a proposal for the Events in CI/CD workstream to become a SIG
=> Propose Events SIG

sigs/sig-events.md
Needs to be reviewed by @e-backmark-ericsson and @afrittoli before being moved out of draft state
=> De-duplicate information in toc and sig-events repo

sigs/sig-chinese-localization.md
The upstream PR is https://github.com/cdfoundation/sig-chinese-localization/pull/1
=> Update the members of Chinese Localization SIG

sigs/proposed.md
=> Add all created SIGs to the listing on the TOC page

CONTRIBUTORS.md
Cleans up TOC contributors and extends the information
=> TOC Contributors cleanup

README.md, proposals/cdevents/cdevents.md
Proposal approved by the Events Sig to join as a project.
=> CD Events Proposal

ROADMAP.md
Adds a small file that points to the CDF Roadmap. Contributes to #111
=> Add ROADMAP.md metadata

sigs/proposed.md
The links in the doc are updated to point to SIG repos.
=> Update links to SIG repos

.github/settings.yml
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add GitHub settings file

README.md
Subj. Welcome @tracyragan and @r2liquibase, and nice that you stay with us Melissa!
=> Update the TOC list after the June elections by the governing board.

CONTRIBUTORS.md
also removed Tracy since she is a TOC member
=> added myself as toc contributor

process/new_project_onboarding.md
- so that it is easy to find
- also fixes a typo
=> Adds direct link to the helpdesk

README.md, process/new_project_onboarding.md
- telemetry link under linux foundation website is still broken.
=> Fixes broken links under Project Guidance

EMERITUS.md, README.md
See the announcement in #163 and the links
=> Remove the TOC Chair status from @oleg-nenashev

elections/2023/README.md
This pull request documents the timeline and process to follow for CDF TOC End user Representative Elections for 2023 in order to ensure transparency and record the process followed by the CDF staff.
=> Document TOC End User Representative Elections 2023

elections/2023/README.md, elections/2023/voters.md
This pull request documents the process to follow together with the timeline for the TOC Project Representative Elections for 2023.
Please note the timeline as well as the upcoming steps in the process as certain artifacts become available on correponding dates.
=> Document TOC Project Representative Elections 2023

elections/2023/voters.md
Voter registration requests were reviewed by the election officer and CDF Staff.
The list of community members whose applications are accepted are added to voters.md file.
=> Update voters.md to include registered voters

process/new_project_onboarding.md
As discussed during the [TOC WG on Jul 18th](https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit#heading=h.3qtcpael34sy), we shall provide projects with guidance about intellectual property and licenses.
Fixes: #28
=> IP Guidance for projects

projects/shipwright/2024-q2.md, projects/shipwright/README.md
=> Provide Project Update for Shipwright

projects/ortelius/2024-q2.md, projects/ortelius/README.md
=> Ortelius Q2 2024 

projects/ortelius/2024-q2.md
Signed-off-by: Steve Taylor <steve@deployhub.com>
=> add links to SecureChainCon recordings for Ortelius

projects/jenkins/2024-q3.md
* Features and Releases
* Grants and Awards
* Elections
* Contribution Trends
* Community updates
* Governance updates
* Security updates
* Infrastructure updates
=> Add Jenkins project update for Q3 2024

projects/tekton/2024-q3.md, projects/tekton/2025-q1.md
This also fixes a link in 2024-q3.md.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
=> Tekton project updates for Q1
